<?php


namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function Category()
{
    $query = $this->getEntityManager()->createQuery(
            'SELECT c.name FROM AppBundle:Category c'
            );

    try
    {
        return $query->getArrayResult();
    }
    catch (\Doctrine\ORM\NoResultException $e)
    {
        return null;
    }
}


    
}






   