<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findOneByTitle($title)
{
    $query = $this->getEntityManager()->createQuery(
            'SELECT p FROM AppBundle:Post p
            WHERE p.title = :title'
        )->setParameter('title', $title);

    try
    {
        return $query->getSingleResult();
    }
    catch (\Doctrine\ORM\NoResultException $e)
    {
        return null;
    }
}


    
}
